### ISSUE TITLE
Is the "Linus Torvaldus" typo on purpose?

### ISSUE THREAD

**Issue by ugultopu** [Carpetsmoker/arp242.net#1]
The correct spelling is "[Torvalds](https://en.wikipedia.org/wiki/Linus_Torvalds)". Is the [typo](https://arp242.net/weblog/i-dont-like-git-but-im-going-to-migrate-my-projects-to-it.html) on purpose?

**Comment by ugultopu** [comment]
Great homepage btw :)

**Comment by Carpetsmoker** [comment]
Thank you :-)

No, this was an accident. I've actually been spelling it as "Torvaldus" for many years, as that's how I pronounce it I guess :-/

Thanks for reporting!
