### ISSUE TITLE
"PHP’s fopen() is broken"'s error handler suck

### ISSUE THREAD

**Issue by divinity76** [Carpetsmoker/arp242.net#12]
the error handler proposed in the article is:
```php
set_error_handler(function($errno, $errstr, $errfile, $errline) {
	throw new ErrorException('error');
});
```
- which completely ignores the error message and severity (ErrorException's constructor has a way to report severity but your code is not using it), and error_reporting flags, and also makes the @ error suppression operator useless. the error reporting flags should be honored, and i think you should use the example from http://php.net/manual/en/class.errorexception.php instead:

```php
function exception_error_handler($severity, $message, $file, $line) {
    if (!(error_reporting() & $severity)) {
        // This error code is not included in error_reporting
        return;
    }
    throw new ErrorException($message, 0, $severity, $file, $line);
}
```

**Comment by Carpetsmoker** [comment]
Thanks!

You're correct it's not a good example, but it's not intended as a proposed error handler (the error message is a fixed string), but rather a minimal example to demonstrate my point.

I'm a bit hesitant to expand it to the "full" example, as that detracts from the point at hand, especially for people who are not intimately familiar with PHP.

I did add a link to the documentation, so people interested in learning more can easily find the correct way to do it.
