### ISSUE TITLE
Hi as of 16:00 CEST the link to your version points back to the page itself - not to the book...

### ISSUE THREAD

**Issue by elbosso** [Carpetsmoker/arp242.net#18]

**Comment by Carpetsmoker** [comment]
Hey, I did some renaming earlier, and everything *should* redirect properly.

Which URL specifically isn't working?

Thanks!

**Comment by elbosso** [comment]
Hi - that was quick!

the first sentence reads "tl;dr: I reformatted Eric S. Raymond’s The Art of Unix Programming for readability; read it here." - the "read it here" is a link that - i suppose - was to link to the actual book but it leads back to https://arp242.net/the-art-of-unix-programming

**Comment by Carpetsmoker** [comment]
Right; that worked for me before, but now it stopped :thinking: Probably a cache issue or some such. I think Netlify magically redirects `link` to `link.html`, even if both exists.

I simply fixed it by renaming the announcement post to `taoup.html`, so now both /the-art-of-unix-programming and /the-art-of-unix-programming.html go to the actual book.

Thanks for reporting!

**Comment by elbosso** [comment]
great work - Thanks!
