### ISSUE TITLE
Translation Permission

### ISSUE THREAD

**Issue by leejh3224** [Carpetsmoker/arp242.net#20]
I read your article `Easy means easy to debug` and really inspired from it.
Thus I want to translate it into Korean and share your great article with my people.
Can I ask you for a permission? Thanks in advance.
Of course, I'll add reference to your original article on top and if you want, I'll let you know the link to translated article.

**Comment by Carpetsmoker** [comment]
Thank you :-) I'm glad it was useful, and I'm honoured that you want to translate it!

Everything is CC-BY-SA license: https://creativecommons.org/licenses/by/4.0/ so you can do what you want with it as long as you keep the attribution. In practice this would mean just a brief notice along the lines of (in English or Korean):

> Translated by leejh3224 from [the original](https://arp242.net/easy.html) by Martin Tournoij. This document is licensed under a [cc-by 4.0 license](https://creativecommons.org/licenses/by/4.0/). 

Or something to that effect.

If you send me the link then I'll add a link to the article.

**Comment by leejh3224** [comment]
Here is a link to an article. https://velog.io/@leejh3224/Easy-means-easy-to-debug
Thanks again for sharing great thoughts!

**Comment by Carpetsmoker** [comment]
Cheers, I added the link.
