### ISSUE TITLE
Typo in footnotes

### ISSUE THREAD

**Issue by gzzo** [Carpetsmoker/arp242.net#4]
In https://arp242.net/weblog/yaml_probably_not_so_great_after_all.html

>Don’t want to start the spaces vs. tabs debate here, **but if tabs** would be allowed I would be able to (temporarily) increase the tab width to a higher number to make it easier to see – this is sort if the point of tabs

Should be "of" instead of "if"

**Comment by Carpetsmoker** [comment]
Oops, thanks!
