### ISSUE TITLE
JSON as config file

### ISSUE THREAD

**Issue by earonesty** [Carpetsmoker/arp242.net#8]
Might want to mention this:

https://github.com/pasztorpisti/json-cfg

I think it addresses the biggest problems with JSON as a config:
 - comments
 - trailing commas
 - better syntax errors

... without adding a bunch of new syntax or complex features.

**Comment by Carpetsmoker** [comment]
Thanks for the suggestion!

This looks like an interesting project, but I'm hesitant to include it as a recommendation/alternative. It doesn't seem to be widely used, and the last commit is over a year ago.

This doesn't mean it's a bad library – it could be a very good library – but from the outset, it's not immediately obvious to me what the quality of it is, and to be honest I don't have the time or interest to do a full review/comparison right now.

This is also why I'm hesitant to include JSON5 or other alternative formats, it *may* look nice *at a glance*, but to really evaluate it requires some more time. I thought YAML was nice at a glance as well, and it wasn't until I extensively used it that I started to realize there are problems with it.

In fact, I will remove the entire "Alternatives" section. Perhaps I will write a separate article about different formats in the future (...or perhaps not...)
